// examples/poc/sveltekit/src/routes/collections/[handle]/+page.svelte
<script lang="ts">
	import CollectionBrowser from '$lib/components/CollectionBrowser.svelte';
	import { getAnalytics, AnalyticsEvent } from '$lib/analytics';
	import type { PageProps } from './$types';

	let { data }: PageProps = $props();

	$effect(() => {
		const handle = data.collection.handle;
		const analytics = getAnalytics();
		if (!analytics) return;
		analytics.publish(AnalyticsEvent.COLLECTION_VIEWED, {
			collection: {
				id: data.collection.id,
				handle: data.collection.handle
			}
		});
		void handle;
	});
</script>

<svelte:head>
	<title>{data.collection.title} — Mock.shop</title>
</svelte:head>

{#key data.collection.handle}
	<CollectionBrowser
		title={data.collection.title}
		description={data.collection.description}
		handle={data.collection.handle}
		dataSearch={data.dataSearch}
		products={data.collection.products.nodes}
		availableFilters={data.collection.products.filters}
	/>
{/key}

// examples/nextjs/app/collections/[handle]/page.tsx
import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { CollectionBrowser } from "@/components/CollectionBrowser";
import { CollectionViewedTracker } from "@/components/CollectionViewedTracker";
import { queryCollection } from "@/lib/collection";
import { getStorefrontClient } from "@/lib/storefront";
import { pageSearchParamsToUrlSearchParams, type PageSearchParams } from "@/lib/url";

type Props = {
  params: Promise<{ handle: string }>;
  searchParams: PageSearchParams;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { handle } = await params;
  const storefrontClient = await getStorefrontClient();
  const result = await queryCollection({
    storefrontClient,
    handle,
    searchParams: new URLSearchParams(),
  });
  const title = result?.collection.title ?? "Collection";
  return { title: `${title} — Mock.shop` };
}

export default async function CollectionPage({ params, searchParams }: Props) {
  const { handle } = await params;
  const urlSearchParams = await pageSearchParamsToUrlSearchParams(searchParams);
  const storefrontClient = await getStorefrontClient();
  const result = await queryCollection({
    storefrontClient,
    handle,
    searchParams: urlSearchParams,
  });
  if (!result) {
    notFound();
  }

  return (
    <>
      <CollectionViewedTracker collection={result.collection} />
      <CollectionBrowser
        mode="collection"
        title={result.collection.title ?? ""}
        description={result.collection.description}
        handle={result.collection.handle}
        dataSearch={urlSearchParams.toString()}
        products={result.products}
        availableFilters={result.availableFilters}
      />
    </>
  );
}
