// examples/sveltekit/src/routes/account/+page.svelte
<script lang="ts">
	let { data } = $props();

	const name = $derived(
		[data.customer?.firstName, data.customer?.lastName].filter(Boolean).join(' ') || 'Customer'
	);
</script>

<main id="main-content" tabindex="-1" class="mx-auto max-w-3xl px-6 py-16" aria-labelledby="account-heading">
	<h1 id="account-heading" class="text-4xl font-black tracking-tight">Account</h1>
	<p class="mt-4 max-w-xl text-black/70">
		Sign in with Shopify Customer Accounts to view your basic account identity.
	</p>

	{#if data.error}
		<p role="alert" class="mt-8 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-900">
			{data.error}
		</p>
	{/if}

	{#if data.customer}
		<section class="bg-paper mt-8 rounded-3xl border border-black/10 p-8" aria-labelledby="identity-heading">
			<h2 id="identity-heading" class="text-sm font-semibold tracking-[0.2em] text-black/55 uppercase">
				Customer identity
			</h2>
			<p class="mt-3 text-2xl font-bold">{name}</p>
			{#if data.customer.emailAddress?.emailAddress}
				<p class="mt-2 text-black/70">{data.customer.emailAddress.emailAddress}</p>
			{/if}
			<form method="post" action="/account/logout" class="mt-8">
				<button
					type="submit"
					class="rounded-full border border-black px-5 py-3 text-sm font-bold hover:bg-black hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-black"
				>
					Log out
				</button>
			</form>
		</section>
	{:else}
		<section class="mt-8 rounded-3xl border border-black/10 p-8" aria-labelledby="login-heading">
			<h2 id="login-heading" class="text-xl font-bold">Sign in</h2>
			<p class="mt-3 max-w-xl text-black/70">Use your customer account to view your name and email for this store.</p>
			{#if data.loginFailed}
				<p role="alert" class="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-900">
					We could not complete your login. Try signing in again.
				</p>
			{/if}
			<a
				href="/account/login"
				class="mt-6 inline-flex rounded-full bg-black px-5 py-3 text-sm font-bold text-white hover:bg-black/80 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-black"
			>
				Log in
			</a>
		</section>
	{/if}
</main>

// experiments/tanstack-start/src/routes/account.tsx
import { createFileRoute } from "@tanstack/react-router";

import { toStorefrontSearch } from "~/lib/search-params";
import { getAccount } from "~/server/account";

export const Route = createFileRoute("/account")({
  validateSearch: toStorefrontSearch,
  loaderDeps: ({ search }) => search,
  // Session state changes outside the router (login/logout are full-page
  // redirects handled by Hydrogen), so never serve this from the loader cache.
  staleTime: 0,
  loader: ({ location }) => getAccount({ data: { search: location.searchStr } }),
  head: () => ({
    meta: [{ title: "Account · CORE" }, { name: "robots", content: "noindex" }],
  }),
  component: AccountPage,
});

const buttonClass =
  "rounded-button button-primary focus-visible:outline-accent inline-flex h-11 items-center justify-center px-5 text-sm font-medium no-underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 motion-safe:transition-[color,background-color,border-color,transform] motion-safe:active:scale-[0.97]";

function AccountPage() {
  const { customer, error, loginFailed } = Route.useLoaderData();
  const name = [customer?.firstName, customer?.lastName].filter(Boolean).join(" ") || "Customer";

  return (
    <main
      id="main-content"
      tabIndex={-1}
      className="px-margin mx-auto w-full max-w-3xl flex-1 py-12"
      aria-labelledby="account-heading"
    >
      <h1 id="account-heading" className="type-display text-on-surface">
        Account
      </h1>
      <p className="text-on-surface-secondary mt-4 max-w-xl">
        Sign in with Shopify Customer Accounts to view your basic account identity.
      </p>

      {error ? (
        <p role="alert" className="border-critical text-critical mt-8 rounded border p-4">
          {error}
        </p>
      ) : null}

      {customer ? (
        <section
          className="border-border rounded-card mt-8 border p-8"
          aria-labelledby="identity-heading"
        >
          <h2 id="identity-heading" className="type-body-sm text-on-surface-secondary uppercase">
            Customer identity
          </h2>
          <p className="type-heading-md text-on-surface mt-3">{name}</p>
          {customer.emailAddress?.emailAddress ? (
            <p className="text-on-surface-secondary mt-2">{customer.emailAddress.emailAddress}</p>
          ) : null}
          {/* Hydrogen's Customer Account handlers serve this POST before routing. */}
          <form method="post" action="/account/logout" className="mt-8">
            <button type="submit" className={buttonClass}>
              Log out
            </button>
          </form>
        </section>
      ) : (
        <section
          className="border-border rounded-card mt-8 border p-8"
          aria-labelledby="login-heading"
        >
          <h2 id="login-heading" className="type-heading-md text-on-surface">
            Sign in
          </h2>
          <p className="text-on-surface-secondary mt-3 max-w-xl">
            Use your customer account to view your name and email for this store.
          </p>
          {loginFailed ? (
            <p role="alert" className="border-critical text-critical mt-4 rounded border p-4">
              We could not complete your login. Try signing in again.
            </p>
          ) : null}
          {/* Plain anchor: `/account/login` is served by Hydrogen before routing. */}
          <a href="/account/login" className={`${buttonClass} mt-6`}>
            Log in
          </a>
        </section>
      )}
    </main>
  );
}
