// examples/sveltekit/src/routes/cart/+page.svelte
<script lang="ts">
	import Cart from '$lib/components/Cart.svelte';
</script>

<svelte:head>
	<title>Cart — Mock.shop</title>
</svelte:head>

<main id="main-content" tabindex="-1" class="mx-auto max-w-3xl px-6 py-16 md:py-20">
	<h1 class="text-6xl font-black tracking-tight md:text-8xl">Cart</h1>
	<div class="mt-12">
		<Cart />
	</div>
</main>

// examples/nuxt/pages/cart.vue
<script setup lang="ts">
useHead({ title: "Cart — Mock.shop" });
</script>

<template>
  <main id="main-content" tabindex="-1" class="mx-auto max-w-3xl px-6 py-16 md:py-20">
    <h1 class="text-6xl font-black tracking-tight md:text-8xl">Cart</h1>
    <div class="mt-12">
      <Cart />
    </div>
  </main>
</template>
