// examples/nuxt/components/Cart.vue
<script setup lang="ts">
import { useCart } from "~/storefront/cart";

const loading = useCart((s) => s.loading);
const lines = useCart((s) => s.data.lines.nodes);

const hasCartContent = computed(() => !loading.value && lines.value.length > 0);
</script>

<template>
  <div>
    <CartRevalidationStatus />
    <CartErrorBanner />
    <CartLineItems />

    <template v-if="hasCartContent">
      <CartTotals />
      <CartDiscountCodes />
      <CartNote />
    </template>
  </div>
</template>

// examples/poc/solid-start/src/components/Cart.tsx
import { Show } from "solid-js";

import { useCart } from "../lib/cart";
import { CartDiscountCodes } from "./CartDiscountCodes";
import { CartErrorBanner } from "./CartErrorBanner";
import { CartLineItems } from "./CartLineItems";
import { CartNote } from "./CartNote";
import { CartRevalidationStatus } from "./CartRevalidationStatus";
import { CartTotals } from "./CartTotals";

export function Cart() {
  const loading = useCart((s) => s.loading);
  const lines = useCart((s) => s.data.lines.nodes);

  return (
    <div>
      <CartRevalidationStatus />
      <CartErrorBanner />
      <CartLineItems />

      <Show when={!loading() && lines().length > 0}>
        <CartTotals />
        <CartDiscountCodes />
        <CartNote />
      </Show>
    </div>
  );
}
