// examples/poc/nuxt/components/CartRevalidationStatus.vue
<script setup lang="ts">
import { computed, ref, watchEffect } from "vue";

import { useCart } from "~/storefront/cart";

const isPending = useCart((state) => state.pending.cost === true || state.revalidating === true);
const hasNetworkErrors = useCart((state) => state.errors.network.length > 0);
const sawPending = ref(false);

watchEffect(() => {
  if (isPending.value) sawPending.value = true;
});

const message = computed(() => {
  if (isPending.value) return "Updating cart totals";
  if (sawPending.value && !hasNetworkErrors.value) return "Cart totals updated";
  return "";
});
</script>

<template>
  <span role="status" class="sr-only">{{ message }}</span>
</template>

// examples/poc/solid-start/src/components/CartRevalidationStatus.tsx
import { createEffect, createSignal } from "solid-js";

import { useCart } from "../lib/cart";

export function CartRevalidationStatus() {
  const isPending = useCart((state) => state.pending.cost === true || state.revalidating === true);
  const hasNetworkErrors = useCart((state) => state.errors.network.length > 0);
  const [sawPending, setSawPending] = createSignal(false);

  createEffect(() => {
    if (isPending()) setSawPending(true);
  });

  const message = () => {
    if (isPending()) return "Updating cart totals";
    if (sawPending() && !hasNetworkErrors()) return "Cart totals updated";
    return "";
  };

  return (
    <span role="status" class="sr-only">
      {message()}
    </span>
  );
}
