// examples/sveltekit/src/lib/components/ShopPayButton.svelte
<script lang="ts">
	import { renderShopPayButton, type ShopPayButtonOptions } from '@shopify/hydrogen';

	let props: ShopPayButtonOptions = $props();

	const html = $derived(renderShopPayButton(props));
</script>

<!-- Trusted markup produced by @shopify/hydrogen; user inputs are escaped by renderShopPayButton. -->
{@html html}

// examples/solid-start/src/components/ShopPayButton.tsx
import { renderShopPayButton, type ShopPayButtonOptions } from "@shopify/hydrogen";

export function ShopPayButton(props: ShopPayButtonOptions) {
  // Trusted markup produced by @shopify/hydrogen; user inputs are escaped by
  // renderShopPayButton.
  return <div style={{ display: "contents" }} innerHTML={renderShopPayButton(props)} />;
}
