// examples/nuxt/components/ShopPayButton.vue
<script setup lang="ts">
import {
  getShopPayButtonAttributes,
  getShopPayButtonStyleProperties,
  loadShopJs,
  SHOP_PAY_BUTTON_TAG_NAME,
  type ShopPayButtonOptions,
} from "@shopify/hydrogen";
import { computed, onMounted, ref } from "vue";

const props = withDefaults(
  defineProps<{
    variants?: ShopPayButtonOptions["variants"];
    paymentOption?: ShopPayButtonOptions["paymentOption"];
    source?: string;
    sourceToken?: string;
    channel?: ShopPayButtonOptions["channel"];
    disabled?: boolean;
    width?: string;
    height?: string;
    borderRadius?: string;
    loadScript?: boolean;
  }>(),
  {
    disabled: false,
    loadScript: true,
  },
);

const storefrontUrl = ref<string>();

onMounted(() => {
  storefrontUrl.value = window.location.origin;
  if (!props.loadScript) return;
  loadShopJs().catch((error: unknown) => {
    console.error("[hydrogen:error:ShopPay] shop-js failed to load:", error);
  });
});

const attrs = computed(() =>
  getShopPayButtonAttributes({
    variants: props.variants,
    paymentOption: props.paymentOption,
    source: props.source,
    sourceToken: props.sourceToken,
    channel: props.channel,
    disabled: props.disabled,
    checkoutUrl: storefrontUrl.value,
  }),
);

const style = computed(() =>
  getShopPayButtonStyleProperties({
    width: props.width,
    height: props.height,
    borderRadius: props.borderRadius,
  }),
);
</script>

<template>
  <component :is="SHOP_PAY_BUTTON_TAG_NAME" v-bind="attrs" :style="style" />
</template>

// examples/sveltekit/src/lib/components/ShopPayButton.svelte
<script lang="ts">
	import {
		getShopPayButtonAttributes,
		getShopPayButtonStyleProperties,
		loadShopJs,
		SHOP_PAY_BUTTON_TAG_NAME,
		type ShopPayButtonOptions
	} from '@shopify/hydrogen';
	import { onDestroy, onMount } from 'svelte';

	let {
		variants,
		checkoutUrl,
		channel = 'headless',
		disabled = false,
		width,
		height,
		borderRadius
	}: ShopPayButtonOptions = $props();

	let container: HTMLDivElement | null = null;
	let button: HTMLElement | null = null;

	function options(): ShopPayButtonOptions {
		return { variants, checkoutUrl, channel, disabled, width, height, borderRadius };
	}

	async function renderButton(currentOptions: ShopPayButtonOptions) {
		if (!container) return;
		await loadShopJs();
		button?.remove();
		button = document.createElement(SHOP_PAY_BUTTON_TAG_NAME);
		for (const [name, value] of Object.entries(getShopPayButtonAttributes(currentOptions))) {
			button.setAttribute(name, value);
		}
		for (const [name, value] of Object.entries(getShopPayButtonStyleProperties(currentOptions))) {
			button.style.setProperty(name, value);
		}
		container.append(button);
	}

	onMount(() => {
		void renderButton(options());
	});

	$effect(() => {
		void renderButton(options());
	});

	onDestroy(() => {
		button?.remove();
	});
</script>

<div bind:this={container}></div>
