// templates/react-router/app/lib/customer-account.ts
import type { ShopifyRequestContext } from "@shopify/hydrogen";
import {
  createCustomerAccountClient,
  createCustomerAccountServerHandlers,
  createCustomerSession,
  type CustomerAccountClient,
  type CustomerSession,
  type WritableCustomerSessionManager,
} from "@shopify/hydrogen/customer-account";
import { createContext } from "react-router";

import { EncryptedCookieCustomerSession } from "./customer-session";
import type { CustomerAccountConfig } from "./shop";

export type CustomerAccountRequestContext =
  | { available: false }
  | {
      available: true;
      client: CustomerAccountClient;
      requestContext: ShopifyRequestContext;
      session: CustomerSession;
      sessionManager: WritableCustomerSessionManager;
    };

export const customerAccountContext = createContext<CustomerAccountRequestContext>();
const customerSessions = new Map<string, CustomerSession>();

export function createCustomerAccountRequestContext(
  requestContext: ShopifyRequestContext,
  config: CustomerAccountConfig,
  sessionManager: WritableCustomerSessionManager,
): Extract<CustomerAccountRequestContext, { available: true }> {
  const session = getCustomerSession(config);

  return {
    available: true,
    client: createCustomerAccountClient({ shopId: config.shopId, requestContext }),
    requestContext,
    session,
    sessionManager,
  };
}

export function createCustomerSessionManager(request: Request, sessionSecret: string) {
  return EncryptedCookieCustomerSession.init(request, sessionSecret);
}

function getCustomerSession(config: CustomerAccountConfig): CustomerSession {
  const key = `${config.shopId}:${config.customerAccountApiClientId}`;
  const existing = customerSessions.get(key);
  if (existing) return existing;

  const session = createCustomerSession({
    shopId: config.shopId,
    customerAccountApiClientId: config.customerAccountApiClientId,
  });
  customerSessions.set(key, session);
  return session;
}

export function createCustomerAccountHandlers(
  customerAccount: Extract<CustomerAccountRequestContext, { available: true }>,
) {
  return createCustomerAccountServerHandlers({
    customerSession: customerAccount.session,
    defaultPostLoginRedirectPathname: "/account",
    loginFailedRedirectPath: "/account?login=failed",
    postLogoutRedirectUri: "/",
  });
}

// examples/solid-start/src/lib/customer-account.ts
import { customerAccountConfig } from "@shared/config";
import { EncryptedCookieCustomerSession } from "@shared/customer-session";
import type { ShopifyRequestContext } from "@shopify/hydrogen";
import * as CAAPI from "@shopify/hydrogen/customer-account";
import { getRequestEvent } from "solid-js/web";

export const ACCOUNT_PATH = "/account";
const CUSTOMER_QUERY = CAAPI.gql(`
  query CurrentCustomer {
    customer {
      firstName
      lastName
      emailAddress {
        emailAddress
      }
    }
  }
`);

export const customerSession = CAAPI.createCustomerSession({
  shopId: customerAccountConfig.shopId,
  customerAccountApiClientId: customerAccountConfig.customerAccountApiClientId,
});

export const customerSessionHandlers = CAAPI.createCustomerAccountServerHandlers({
  customerSession,
  defaultPostLoginRedirectPathname: ACCOUNT_PATH,
  postLogoutRedirectUri: "/",
});

export async function createCustomerSessionManager(request: Request) {
  return EncryptedCookieCustomerSession.init(request, customerAccountConfig.sessionSecret);
}

export function createRequestCustomerAccountClient(
  requestContext: Parameters<typeof CAAPI.createCustomerAccountClient>[0]["requestContext"],
) {
  return CAAPI.createCustomerAccountClient({
    shopId: customerAccountConfig.shopId,
    requestContext,
  });
}

export function getRequestCustomerAccountContext() {
  const event = getRequestEvent();
  const { customerAccountClient, customerSessionManager, shopifyRequestContext } =
    event?.locals ?? {};

  if (!customerAccountClient || !customerSessionManager || !shopifyRequestContext) {
    throw new Error("Customer Account context was not created for this server request.");
  }

  return { customerAccountClient, customerSessionManager, shopifyRequestContext };
}

export type CustomerAccountLocals = {
  customerAccountClient: CAAPI.CustomerAccountClient;
  customerSessionManager: CAAPI.WritableCustomerSessionManager;
  shopifyRequestContext: ShopifyRequestContext;
};

type CustomerAccountPageDataOptions = {
  request: Request;
  requestContext: ShopifyRequestContext;
  sessionManager: CAAPI.WritableCustomerSessionManager;
  customerAccount: CAAPI.CustomerAccountClient;
};

export async function getCustomerAccountPageData({
  request,
  requestContext,
  sessionManager,
  customerAccount,
}: CustomerAccountPageDataOptions) {
  const requestUrl = new URL(request.url);
  const loginFailed = requestUrl.searchParams.get("login") === "failed";
  const accessToken = await customerSession.getAccessToken(sessionManager, requestContext);

  if (!accessToken) return { customer: null, error: null, loginFailed };

  try {
    const { data, errors } = await customerAccount.graphql(CUSTOMER_QUERY, { accessToken });
    return {
      customer: errors ? null : data.customer,
      error: errors?.[0]?.message ?? null,
      loginFailed,
    };
  } catch {
    return {
      customer: null,
      error: "Customer Account API request failed. Try again later.",
      loginFailed,
    };
  }
}
