// examples/nextjs/app/blogs/news/[handle]/page.tsx
import { gql } from "@shopify/hydrogen";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { getStorefrontClient } from "@/lib/storefront";

const ARTICLE_QUERY = gql(`
  query Article($handle: String!) {
    blog(handle: "news") {
      articleByHandle(handle: $handle) {
        handle
        title
        publishedAt
        contentHtml
      }
    }
  }
`);

const dateFormatter = new Intl.DateTimeFormat("en-US", { dateStyle: "long" });

type Props = { params: Promise<{ handle: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { handle } = await params;
  const storefrontClient = await getStorefrontClient();
  const { data } = await storefrontClient.graphql(ARTICLE_QUERY, {
    variables: { handle },
  });
  const title = data?.blog?.articleByHandle?.title ?? "Article";
  return { title: `${title} — Mock.shop` };
}

export default async function ArticlePage({ params }: Props) {
  const { handle } = await params;
  const storefrontClient = await getStorefrontClient();
  const { data } = await storefrontClient.graphql(ARTICLE_QUERY, {
    variables: { handle },
  });
  const article = data?.blog?.articleByHandle;
  if (!article) {
    notFound();
  }

  return (
    <main className="mx-auto max-w-3xl px-6 py-16 md:py-24">
      <article>
        <header className="text-center">
          <h1 className="text-5xl font-black tracking-tight md:text-7xl">{article.title}</h1>
          <p className="mt-6 text-sm text-black/60">
            {dateFormatter.format(new Date(article.publishedAt))}
          </p>
        </header>

        <div
          className="mt-16 text-base leading-relaxed text-black/80 *:first:mt-0 md:text-lg [&>h3]:mt-12 [&>h3]:text-3xl [&>h3]:font-black [&>h3]:tracking-tight [&>h3]:text-black md:[&>h3]:text-4xl [&>p]:mt-6"
          dangerouslySetInnerHTML={{ __html: article.contentHtml }}
        />

        <div className="mt-20 border-t border-black/10 pt-8">
          <Link
            href="/blogs/news"
            className="inline-flex items-center gap-2 text-sm font-semibold hover:opacity-60"
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <path d="M19 12H5" />
              <path d="m12 19-7-7 7-7" />
            </svg>
            Back to News
          </Link>
        </div>
      </article>
    </main>
  );
}

// examples/nuxt/pages/blogs/news/[handle].vue
<script setup lang="ts">
import { gql } from "@shopify/hydrogen";

const ARTICLE_QUERY = gql(`
  query Article($handle: String!) {
    blog(handle: "news") {
      articleByHandle(handle: $handle) {
        handle
        title
        publishedAt
        contentHtml
      }
    }
  }
`);

type Article = {
  handle: string;
  title: string;
  publishedAt: string;
  contentHtml: string;
};

const dateFormatter = new Intl.DateTimeFormat("en-US", { dateStyle: "long" });

const route = useRoute();
const handle = computed(() => route.params.handle as string);
const { $storefrontClient } = useNuxtApp();

const { data } = await useAsyncData(
  computed(() => `article-${handle.value}`),
  async () => {
    const response = await $storefrontClient.graphql(ARTICLE_QUERY, {
      variables: { handle: handle.value },
    });
    return response.data as { blog: { articleByHandle: Article | null } | null } | null;
  },
  { watch: [handle] },
);

const article = computed(() => data.value?.blog?.articleByHandle);

if (!article.value) {
  throw createError({ statusCode: 404, statusMessage: "Article not found" });
}

useHead({ title: () => `${article.value?.title ?? "Article"} — Mock.shop` });
</script>

<template>
  <main v-if="article" class="mx-auto max-w-3xl px-6 py-16 md:py-24">
    <article>
      <header class="text-center">
        <h1 class="text-5xl font-black tracking-tight md:text-7xl">
          {{ article.title }}
        </h1>
        <p class="mt-6 text-sm text-black/60">
          {{ dateFormatter.format(new Date(article.publishedAt)) }}
        </p>
      </header>

      <!-- eslint-disable-next-line vue/no-v-html -->
      <div
        class="mt-16 text-base leading-relaxed text-black/80 *:first:mt-0 md:text-lg [&>h3]:mt-12 [&>h3]:text-3xl [&>h3]:font-black [&>h3]:tracking-tight [&>h3]:text-black md:[&>h3]:text-4xl [&>p]:mt-6"
        v-html="article.contentHtml"
      />

      <div class="mt-20 border-t border-black/10 pt-8">
        <NuxtLink
          to="/blogs/news"
          class="inline-flex items-center gap-2 text-sm font-semibold hover:opacity-60"
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <path d="M19 12H5" />
            <path d="m12 19-7-7 7-7" />
          </svg>
          Back to News
        </NuxtLink>
      </div>
    </article>
  </main>
</template>
